name = "PortMidi"
uuid = "42b16160-194f-40b3-8419-7a13c10fa643"
authors = ["SteffenPL <steffen.plunder@web.de> and contributors"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
PortMidi_jll = "6b227df9-c220-5195-838c-e1464939a66f"

[compat]
PortMidi_jll = "2.0.4"
julia = "1.6"
CEnum = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
