name = "PortMidi"
uuid = "42b16160-194f-40b3-8419-7a13c10fa643"
authors = ["SteffenPL <steffen.plunder@web.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
