[general]
library_name = "libportmidi"
output_file_path = "../src/PortMidi.jl"
module_name = "PortMidi"
jll_pkg_name = "PortMidi_jll"

use_julia_native_enum_type = true

prologue_file_path = "prologue.jl"
epilogue_file_path = "epilogue.jl"

export_symbol_prefixes = ["Pm"]
output_ignorelist = ["TRUE", "FALSE"]